# Generated by Django 2.1.2 on 2018-12-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoursCalc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoursday',
            name='break_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
