# Generated by Django 2.1.2 on 2018-12-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoursCalc', '0002_hoursday_break_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoursday',
            name='duration',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
