# Generated by Django 2.1.2 on 2018-12-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoursCalc', '0003_auto_20181210_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoursday',
            name='duration',
            field=models.FloatField(default=0),
        ),
    ]
