# Generated by Django 2.1.2 on 2018-12-31 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoursCalc', '0005_auto_20181218_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='month',
            name='name',
        ),
        migrations.RemoveField(
            model_name='week',
            name='month',
        ),
        migrations.DeleteModel(
            name='Month',
        ),
        migrations.DeleteModel(
            name='Week',
        ),
    ]
