# Generated by Django 2.1.2 on 2019-01-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoursCalc', '0006_auto_20181231_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='description',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
    ]
